export default interface IUsers{
    userID?:number,
    displayName:string,
    firstName:string,
    middleName:string,
    lastName:string,
    mobileNumber:string,
    email:string,
    role?:string,
    address?:string,
    gender?:string,
    martialStatus?:string,
    bloodGroup?:string,
    dOB?:Date,
    loginCreated?:Date,
    lastSeen?:Date,
    about?:string,
    profSum?:string,
    profilePic?:string,
    isActive?:boolean,
    isContactHide?:boolean,
    isProfSumHide?:boolean,
    rowCreatedOn?:Date,
    rowCreatedBy?:number,
    rowDeletedBy?:number

}

export const DefaultUser:IUsers=
{
    userID:0,
    displayName:'',
    firstName:'',
    middleName:'',
    lastName:'',
    mobileNumber:'',
    email:'',
    role:'',
    address:'',
    gender:'',
    martialStatus:'',
    bloodGroup:'',
    dOB:new Date(),
    loginCreated:new Date(),
    lastSeen:new Date(),
    about:'',
    profSum:'',
    profilePic:'',
    isActive:false,
    isContactHide:false,
    isProfSumHide:false,
    rowCreatedOn:new Date(),
    rowCreatedBy:0,
    rowDeletedBy:0
}